services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    ports:
      - "5080:5080" # OpenObserve UI & API
    environment:
      - ZO_ROOT_USER_EMAIL=root@example.com
      - ZO_ROOT_USER_PASSWORD=root
      - ZO_LOCAL_MODE=true # ローカル開発向けの設定
      - ZO_DATA_DIR=/data
    volumes:
      - ./openobserve-data:/data
    restart: unless-stopped
